#!/bin/sh

## notes to self
# link this to /usr/bin/sway_rofi
##
# probably loose whatever perfomance is gained by ripgrep by checking for it...

if command -v rg >/dev/null; then
	RG="true"
fi

SCREEN_POS=$(swaymsg -t get_outputs \
	| jq -r \
	'.[] | select(.focused).rect | "\(.width)x\(.height)\\+\(.x)\\+\(.y)"')

echo "$SCREEN_POS"

# ripgrep
if [ -z "$RG" ]; then
	XWAYLAND_OUTPUT=$(xrandr | grep -oP "[A-Za-z- ]+[0-9]+(?= [a-z]+ $SCREEN_POS)")
else
	XWAYLAND_OUTPUT=$(xrandr | rg -oP "[A-Za-z- ]+[0-9]+(?= [a-z]+ $SCREEN_POS)")
fi

if [ -z "$XWAYLAND_OUTPUT" ] ; then
	exec rofi -e "Failed to get XWAYLAND_OUTPUT, likely position inconsistencies \
between sway and rofi"
fi

if [ -z "$RG" ]; then
	MONITOR_ID=$(rofi --help | grep $XWAYLAND_OUTPUT -B1 \
		| sed -sr '/ID/!d;s/[^:]*:\s([0-9])/\1/')
else
	MONITOR_ID=$(rofi --help | rg $XWAYLAND_OUTPUT -B1 \
		| sed -sr '/ID/!d;s/[^:]*:\s([0-9])/\1/')
fi

if [ -z "$MONITOR_ID" ]; then
	exec rofi -e "Failed to get monitor id for output: $XWAYLAND_OUTPUT"
fi

exec rofi -m $MONITOR_ID $@ </dev/stdin
